### ISSUE TITLE
NameError: name 'VIDEO_RESIZE' is not defined

### ISSUE THREAD

**Issue by oximi123** [Oryx-mllm/Oryx#22]
Hi, when I run the inference.py, it gives me the following error:

```
Traceback (most recent call last):
  File "/home/zhuyifei/code/Oryx-main/inference.py", line 192, in <module>
    eval_model(args)
  File "/home/zhuyifei/code/Oryx-main/inference.py", line 142, in eval_model
    frame = process_anyres_video_genli(frame, image_processor)
  File "/home/zhuyifei/code/Oryx-main/oryx/mm_utils.py", line 182, in process_anyres_video_genli
    if VIDEO_RESIZE is not None:
NameError: name 'VIDEO_RESIZE' is not defined
```

I check the following code where `VIDEO_RESIZE` is defined, it indicates that if I do not declare it in `os.environ`, it will never be initialized. So how can I correctly initialize it?

```
if 'VIDEO_RESIZE' in os.environ:
    # highresxpatch
    VIDEO_RESIZE = os.environ['VIDEO_RESIZE']
    video_base, video_ps = VIDEO_RESIZE.split('x')
    video_base = int(video_base)
    video_ps = int(video_ps)
    print(f"VIDEO_RESIZE is set as {VIDEO_RESIZE}, {video_base}, {video_ps}")
else:
    HIGHRES_BASE = None
```
    
By the way, what is the meaning of `images_highres` in the generate method of Oryx model? What will it influence if I set it to different value?

```
        output_ids = model.generate(
            inputs=input_ids,
            images=video_data[0][0],
            images_highres=video_data[0][1],
            modalities=video_data[2],
            do_sample=True if args.temperature > 0 else False,
            temperature=args.temperature,
            top_p=args.top_p,
            num_beams=args.num_beams,
            max_new_tokens=128,
            use_cache=True,
        )
```

**Comment by dongyh20** [comment]
Hi, for inference, you may check the inference.sh in the codebase. image_highres indicates the images or videos with the original resolution. If VIDEO_RESIZE='0x64', it will be the native resolution, if VIDEO_RESIZE='384x64', it will resize each frame of the video to around 384*384 pixels, while maintain the original ratio of images.
